### ISSUE TITLE
Why does SQS Extract method not accept a context? 

### ISSUE THREAD

**Issue by MukeshGKastala** [udhos/opentelemetry-trace-sqs#1]
Instead of https://github.com/udhos/opentelemetry-trace-sqs/blob/v1.1.2/otelsqs/otelsqs.go#L130, can we accept a context instead?

**Comment by udhos** [comment]
Yes, I think we can pass a context.

I am unsure why it would be better, can you share your thoughts?

You can send PR if you want to. I expect to look at it by tomorrow.

**Comment by udhos** [comment]
@MukeshGKastala New version accepting context as argument:

https://github.com/udhos/opentelemetry-trace-sqs/blob/v1.2.0/otelsqs/otelsqs.go#L129
